const DATA_INPUT_HEADER = {
    "Nom": "Nom",
    "Prénom": "Prénom",
    "Téléphone": "Téléphone",
    "Adresse": "Adresse",
    "Ville": "Ville",
    "Code postal": "Code postal",
    "Statut": "Statut",
    "agent": "Agent",
    "Campagne": "Campagne",
    "Liste d'appel": "Liste d'appel",
    "Date d'appel": "Date d'appel",
    "forme_juridique": "Forme juridique",
    "nace_code": "Code Nace",
    "nace_description": "Description Nace",
    "contact_position": "Position contact",
    "numero_entreprise": "Numéro entreprise",
    "province": "Province",
    "website": "Website",
    "sexe": "Sexe",
    "mail_direct": "Mail direct",
    "mail_general": "Mail général",
    "gsm": "GSM",
    "tel_direct": "Téléphone direct",
    "commentaire_appel": "Commentaire appel",
    "prenom": "Prénom inter",
    "nom2": "Nom inter",
    "prenom inter": "Prénom inter",
    "nom inter": "Nom inter",
    "agent": "Agent",
};

export default {
    DATA_INPUT_HEADER,
};