const DATA_INPUT_HEADER = {
    "nom": "Nom",
    "prénom": "Prénom",
    "téléphone": "Téléphone",
    "adresse": "Adresse",
    "ville": "Ville",
    "code_postal": "Code postal",
    "statut": "Statut",
    "agent": "Agent",
    "campagne": "Campagne",
    "liste_d'appel": "Liste d'appel",
    "date_d'appel": "Date d'appel",
    "forme_juridique": "Forme juridique",
    "nace_code": "Code Nace",
    "nace_description": "Description Nace",
    "contact_position": "Position contact",
    "numero_entreprise": "Numéro entreprise",
    "province": "Province",
    "website": "Website",
    "sexe": "Sexe",
    "mail_direct": "Mail direct",
    "mail_general": "Mail général",
    "gsm": "GSM",
    "tel_direct": "Téléphone direct",
    "commentaire_appel": "Commentaire appel",
    "prenom": "Prénom inter",
    "nom2": "Nom inter",
    "prenom_inter": "Prénom inter",
    "nom_inter": "Nom inter",
};

export default {
    DATA_INPUT_HEADER,
};